sudo: required

language: cpp

os:
  - linux

# whitelist
branches:
  only:
    - master
    - development

#env:
#  - CONFIG=Release
#  - CONFIG=Debug

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-add-repository -y ppa:beineri/opt-qt55
  - sudo apt-get update -qq
  - sudo apt-get install -y qt55base qt55-meta-full qtcreator-latest
  - qmake -v
  - git submodule update --init --recursive

script:
  - cd src
  - qmake
  - make -j 3
